# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
try:
    from clients.grpc_stubs import niffler_currency_pb2 as niffler__currency__pb2
except ImportError:
    import niffler_currency_pb2 as niffler__currency__pb2  # type: ignore

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    import warnings
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in niffler_currency_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or regenerate the stubs using grpcio-tools<={GRPC_VERSION}.',
        RuntimeWarning
    )


class NifflerCurrencyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllCurrencies = channel.unary_unary(
                '/guru.qa.grpc.niffler.NifflerCurrencyService/GetAllCurrencies',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=niffler__currency__pb2.CurrencyResponse.FromString,
                _registered_method=True)
        self.CalculateRate = channel.unary_unary(
                '/guru.qa.grpc.niffler.NifflerCurrencyService/CalculateRate',
                request_serializer=niffler__currency__pb2.CalculateRequest.SerializeToString,
                response_deserializer=niffler__currency__pb2.CalculateResponse.FromString,
                _registered_method=True)


class NifflerCurrencyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllCurrencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NifflerCurrencyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllCurrencies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCurrencies,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=niffler__currency__pb2.CurrencyResponse.SerializeToString,
            ),
            'CalculateRate': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRate,
                    request_deserializer=niffler__currency__pb2.CalculateRequest.FromString,
                    response_serializer=niffler__currency__pb2.CalculateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guru.qa.grpc.niffler.NifflerCurrencyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guru.qa.grpc.niffler.NifflerCurrencyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NifflerCurrencyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllCurrencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guru.qa.grpc.niffler.NifflerCurrencyService/GetAllCurrencies',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            niffler__currency__pb2.CurrencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guru.qa.grpc.niffler.NifflerCurrencyService/CalculateRate',
            niffler__currency__pb2.CalculateRequest.SerializeToString,
            niffler__currency__pb2.CalculateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
